/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Fetch the current markdown source of a docs page */
		get: operations["getSource"];
		put?: never;
		/** Submit an edited docs page as a pull request */
		post: operations["createSubmission"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @description Docs-relative markdown path; the pattern rejects traversal outside the docs tree */
		SourcePath: string;
		Submission: {
			title: string;
			/** @description Full replacement content of the edited page */
			content: string;
			author?: {
				name?: string;
				contact?: "" | string;
			};
			/** @default en */
			lang: string;
			sourcePath: components["schemas"]["SourcePath"];
		};
		Error: {
			error: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getSource: {
		parameters: {
			query: {
				path: components["schemas"]["SourcePath"];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Raw markdown source */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": string;
				};
			};
			/** @description Invalid path */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Error"];
				};
			};
			/** @description GitHub request failed */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Error"];
				};
			};
		};
	};
	createSubmission: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Submission"];
			};
		};
		responses: {
			/** @description Pull request opened */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						url: string;
					};
				};
			};
			/** @description Submission failed validation */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Error"];
				};
			};
			/** @description GitHub request failed */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Error"];
				};
			};
		};
	};
}
